export { modals } from './modal'
export { sliders } from './sliders'
export { formsFeedback } from './forms'
export { mask } from './mask'
export { checkNameInputs } from './checkNameInputs'
export { checkEmailInputs } from './checkEmailInputs'